node {
    
    stage('Checkout') {
       git 'git@github.com:Adapaka2023/Docker-Lab.git'
    }
    stage('Build docker image') {
       sh "docker build -t rameshadapaka/nodeapp:$BUILD_NUMBER ."
    }
    stage('login to dockerhub') {
         withCredentials([usernamePassword(credentialsId: 'DockerCredentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_USERNAME} --password-stdin"
                }
    }
    stage('push image') {
       sh "docker push rameshadapaka/nodeapp:$BUILD_NUMBER"
    }
    stage('logout to dockerhub') {
       sh "docker logout"
    }
}
